### PR TITLE
Sync Groups on Login Support

### PR DESCRIPTION
**Pull request by bmlong137**
I have a requirement where we cannot use LDAP and there is no service call that can be made to sync users/groups or their membership.  All of it has to be determined when the user signs in.  The identity service is also based on Ping Identity.

I decided to try out this module combined with Alfresco Identity Service (keycloak server).  All worked except for that sync.  So I added sync functionality where I felt appropriate.  It certainly needs some work.  However, it is a first pass that I will improve upon over the coming months.

So I am putting this out there in case you want to incorporate it or track it as a separate branch.

### CODE REVIEW

**Comment by AFaust** [comment]
Hmm... so far I have intentionally kept out any kind of authority synchronisation during login handling. For permission purposes, it is not necessary. The only case for it being relevant that I see would be lookup by other users or group-based resolutions in background processing jobs or actions triggered by other users. For this I had considered the LDAP-like synch support that is already part of the module to be sufficient. I did not want to create authorities and/or add members based on the (dynamically mapped) authorities from the ID / access token, as it would not allow for a clean undo, e.g. if mappings change / role + group memberships in Keycloak change.

**Comment by bmlong137** [comment]
There is no real sync possibility with the upstream system at this time.  I could use your sync with keycloak, which is then sync'd only on login to the upstream system.  But I would suspect we would run into the same situation.  I wanted to implement it in a way that did not rely too much on keycloak specifics and rest more on OIDC.

Feel free to reject.  I am toying with possible solutions at this time and have a short deadline.  Just needed to get a working solution out there.  I am moving on to providing authority sync to APS, which will surely be more painful.

**Comment by AFaust** [comment]
What I would have absolutely no problem with is if a kind of `KeycloakLoginProcessor` interface were to be added in the authentication component with a single `onKeycloakLogin(IdToken, AccessToken)` operation, with support for registration of a variable set of processors. E.g. the current mapping of person properties would be changed to an implementation of that interface. That interface would also be the basis of adding functionality like the one you are proposing. If implemented as a processor in this module, I would prefer to have some finer control, e.g. "map as member of existing groups only" vs. "map as member, create groups if missing" etc...

**Comment by bmlong137** [comment]
I will note that for my next revision before the next pull request.  Thanks for the feedback.

**Comment by bmlong137** [comment]
Looks like you want want pluggable processors for extended implementations on how to handle logins.  That should be trivial.  And turning on/off certain features within it (existing groups for instance) would also be trivial.  Good ideas.

**Comment by AFaust** [comment]
Yeah. Though my initial "reservation" was because I had myself rejected this kind of sync during first implementation, I can see the high level use case of doing some kind of (partial) sync during login. The processor / plugin idea is based mostly on the consideration that there rarely is a one-size-fits-all solution. E.g. I could very well see that there might be different requirements / restrictions to this kind of synch, e.g. an additional filtering step to not handle all the mapped authorities (i.e. exclude GROUP_ALFRESCO_ADMINISTRATORS because that would forever grant admin privileges), so I'd like end users to have the flexibility of disabling any default processor or replacing it with one of their own. It would also mean that even in the case I wake up one day to reject the idea of doing the mapping as part of the core module, you'd still have a way to plugin your handling regardless.

**Comment by AFaust** [comment]
Instead of using the `GrantedAuthority` array, a processor could use [the same or a similarly configured set of role claim mappers to determine which authorities need to be synched](https://github.com/Acosix/alfresco-keycloak/blob/master/repository/src/main/globalConfig/subsystems/Authentication/keycloak/keycloak-authentication.properties#L38). There already is an existing re-use of the underlying interfaces in the RoleService which exposes the authorities for permission management in Share UI (since I don't use any ADF-based apps, I have yet to look at what it would take to support that).

**Comment by bmlong137** [comment]
We are using ADF, so I'll be seeing how all this goes with that and will provide feedback.

**Comment by bmlong137** [comment]
I have made changes to implement this feature outside the KeycloakAuthenticationComponent.  A new pull request will be submitted.

**Pull request closed without merging**
